#!/bin/bash

# Function to parse input arguments separated by '§'
# If the directory part is empty, it defaults to the current working directory
lettura_p_p() {
    IFS='§' read -r pref par cart <<< "$1"
    cart="${cart:-$(pwd)}"
    echo "$pref|$par|$cart"
}

# Parse the input using the '|' delimiter generated by the function
IFS='|' read -r pref par cart <<< "$(lettura_p_p "$1")"

# Validate that the target directory exists
if [[ ! -d "$cart" ]]; then
    echo "Error: the directory '$cart' does not exist."
    exit 1
fi

# Change to the target directory
cd "$cart" || exit 1

# Use an array to store files matching the parameter pattern
files=( $par )

# Check if any files were found
if [[ ! -e "${files[0]}" ]]; then
    echo "No files found matching the pattern '$par'."
    exit 1
fi

# Show a dry-run simulation of the renaming process
echo "--- Simulation: Renaming in $cart ---"
for file in "${files[@]}"; do
    echo "  [SIM] '$file' -> '$pref$file'"
done

# Ask for user confirmation before applying changes
read -r -p "Confirm renaming ${#files[@]} files? (s/n): " risposta
if [[ "$risposta" == "s" ]]; then
    # Perform the move (rename) operation
    for file in "${files[@]}"; do
        mv -v "$file" "$pref$file"
    done
    echo "Operation completed."
else
    echo "Operation cancelled."
fi